version: '3'
services:
  node_app:
    env_file: 
      - dev.env
    environment:
      - PORT=9000
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:9000"
    volumes:
      - .:/usr/app